<a href="https://colab.research.google.com/github/souru98/Ml-Iris_DataSet/blob/main/Sourabh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [1]:
import numpy as np
import pandas as pd

Load The Iris DataSet And Check Featues


In [2]:
#Import the load_iris function from datasets modules.
from sklearn.datasets import load_iris

In [3]:
#create bunch object containing iris dataset and its attributes.
iris=load_iris()

In [4]:
#keys of Iris Data
print("Keys of iris: \n{}" .format(iris.keys()))

Keys of iris: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
#Type Of Data
print("Type of data: {}".format(type(iris['data'])))

Type of data: <class 'numpy.ndarray'>


In [7]:
#print the complete iris data
iris.data
print("Data:\n{}".format(iris['data']))

Data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 

In [8]:
#We can get a quick description of data
iris.DESCR
print("Description:\n{}".format(iris['DESCR']))

Description:
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ====

In [9]:
#column names
iris.feature_names
print("Feature names: \n{}".format(iris['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [10]:
#FileName
iris.filename
print("File Name: \n{}".format(iris['filename']))

File Name: 
/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/iris.csv


In [11]:
#Rows and Columns Of DAta
print("Shape of data: {}".format(iris['data'].shape))

Shape of data: (150, 4)


In [12]:
#Printing Some Part Of Data
print("First five rows of data:\n{}".format(iris['data'][:10]))

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [13]:
#Type of Target
print("Type of target: {}".format(type(iris['target'])))

Type of target: <class 'numpy.ndarray'>


In [14]:
#shape of Target
print("Shape of target: {}".format(iris['target'].shape))

Shape of target: (150,)


In [15]:
#Target
iris.target
print("Target:\n{}".format(iris['target']))   # 0 means sentosa,1 means versicolor,and 2 means virginica

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**0** means sentosa,1 means versicolor,and 2 means virginica

In [16]:
#Target Names
iris.target_names
print("Target Names:\n{}".format(iris['target_names']))

Target Names:
['setosa' 'versicolor' 'virginica']


Spliting dataset into training set and test set

In [17]:
# Let's split dataset into training set and test set, to check later on whether or not our classifier works correctly
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris['data'],iris['target'],random_state=0
)

In [18]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


k nearest neighbors model for ml

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [20]:
#Training the Data 
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [21]:
#Predictions
X_new = np.array([[8,4,1.9,0.6]])

print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [22]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("target name: {}".format(
    iris['target_names'][prediction]))

Prediction: [0]
target name: ['setosa']


In [23]:
#Evaluatation
y_pred = knn.predict(X_test)
print("predictions:\n {}".format(y_pred))

predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [24]:
print("score: {}".format(np.mean(y_pred==y_test)))

score: 0.9736842105263158
